local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 9
      height: 9
      resolution: 0.05
      trinary_costmap: false
      footprint: "[ [0.45, 0.3], [0.45, -0.3], [-0.45, -0.3], [-0.45, 0.3] ]"
      plugins: ["static_layer"]
      static_layer:
        map_subscribe_transient_local: False
        plugin: "nav2_costmap_2d::StaticLayer"
        subscribe_to_updates: false
        map_topic: "/map_static"
        transform_tolerance: 0.3
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True