twist_mux:
  ros__parameters:
    output_stamped: false
    topics:
      navigation:
        topic: cmd_vel
        priority: 20
        timeout: 0.1
        stamped : false
      joystick:
        topic: joy_teleop/cmd_vel
        priority: 50
        timeout: 0.1
        stamped : false
      zero_twist:
        topic: zero_twist/cmd_vel
        priority: 10
        timeout: 0.1
        stamped : false